/*
Admin
*/

//Company
export const CREATE_COMPANY = 'CREATE_COMPANY'
export const UPDATE_COMPANY = 'UPDATE_COMPANY'
export const DELETE_COMPANY = 'DELETE_COMPANY'
export const GET_COMPANY_DETAILS = 'GET_COMPANY_DETAILS'
export const UPDATE_COMPANY_DETAILS = 'UPDATE_COMPANY_DETAILS'

// Dashboard
export const GET_BARCHART_DATA = 'GET_BARCHART_DATA'
export const GET_TODAYS_ATTENDANCE = 'GET_TODAYS_ATTENDANCE'

// Employee
export const GET_ALL_EMPLOYEES = 'GET_ALL_EMPLOYEES'
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE'
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE'
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE'

// Loan
export const GET_ALL_LOANS = 'GET_ALL_LOANS'
export const CREATE_LOAN = 'CREATE_LOAN'
export const UPDATE_LOAN = 'UPDATE_LOAN'
export const DELETE_LOAN = 'DELETE_LOAN'
export const REPAY_LOAN = 'REPAY_LOAN'
export const GET_LOAN_TITLES = 'GET_LOAN_TITLES'
export const GET_LOAN_REQUESTS = 'GET_LOAN_REQUESTS'
export const UPDATE_LOAN_REQUEST = 'UPDATE_LOAN_REQUEST'

// Leave
export const GET_ALL_LEAVES = 'GET_ALL_LEAVES'
export const CREATE_LEAVE = 'CREATE_LEAVE'
export const UPDATE_LEAVE = 'UPDATE_LEAVE'
export const DELETE_LEAVE = 'DELETE_LEAVE'
export const GET_LEAVE_REQUESTS = 'GET_REQUEST_LEAVES'
export const UPDATE_LEAVE_REQUEST = 'UPDATE_REQUEST_LEAVE'

// User
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const CREATE_USER = 'CREATE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const DELETE_USER = 'DELETE_USER'

// Task 
export const GET_ALL_TASKS = 'GET_ALL_TASKS'
export const CREATE_TASK = 'CREATE_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const DELETE_TASK = 'DELETE_TASK'

// Public holiday
export const GET_ALL_HOLIDAYS = 'FETCH_HOLIDAYS'
export const CREATE_HOLIDAY = 'CREATE_HOLIDAY'
export const UPDATE_HOLIDAY = 'UPDATE_HOLIDAY'
export const DELETE_HOLIDAY = 'DELETE_HOLIDAY'

// Sites
export const GET_ALL_SITES = 'GET_ALL_SITES'
export const CREATE_SITE = 'CREATE_SITE'
export const UPDATE_SITE = 'UPDATE_SITE'
export const DELETE_SITE = 'DELETE_SITE'


// Annoucement
export const GET_ALL_ANNOUNCEMENT = 'GET_ALL_ANNOUNCEMENT'
export const CREATE_ANNOUNCEMENT = 'CREATE_ANNOUNCEMENT'
export const UPDATE_ANNOUNCEMENT = 'UPDATE_ANNOUNCEMENT'
export const DELETE_ANNOUNCEMENT = 'DELETE_ANNOUNCEMENT'
export const GET_TODAYS_ANNOUNCEMENT = 'FETCH_TODAYS_ANNOUNCEMENT'

// Attendance
export const GET_ALL_ATTENDANCE = 'GET_ALL_ATTENDANCE'
export const GET_ABSENT_EMPLOYEES = 'GET_ABSENT_EMPLOYEES'
export const GET_PRESENT_EMPLOYEES = 'GET_PRESENT_EMPLOYEES'
export const GET_LATE_EMPLOYEES = 'GET_LATE_EMPLOYEES'
export const GET_LEAVE_EMPLOYEES = 'GET_LEAVE_EMPLOYEES'


/*
Employee
*/

// Dashboard
export const GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA'
export const CLEAR_DASHBOARD_DATA = 'CLEAR_DASHBOARD_DATA'

// Break 
export const START_BREAK = 'START_BREAK'
export const END_BREAK = 'END_BREAK'
export const BREAK_TIME = 'BREAK_TIME'

// Attendance
export const GET_USER_ATTENDANCE = 'GET_USER_ATTENDANCE'

// Leave
export const GET_ALL_LEAVE_REQUESTS = 'GET_ALL_LEAVE_REQUESTS'
export const CREATE_LEAVE_REQUEST = 'CREATE_LEAVE_REQUEST'
export const DELETE_LEAVE_REQUEST = 'DELETE_LEAVE_REQUEST'

// Loan
export const UPDATE_USER_LOAN = 'UPDATE_USER_LOAN'
export const GET_ALL_LOAN_REQUESTS = 'GET_ALL_LOAN_REQUESTS'
export const CREATE_LOAN_REQUEST = 'CREATE_LOAN_REQUEST'
export const DELETE_LOAN_REQUEST = 'DELETE_LOAN_REQUEST'
export const USER_LOAN_DETAILS = 'USER_LOAN_DETAILS'

// Task
export const GET_EMPLOYEE_TASKS = 'GET_EMPLOYEE_TASKS'
export const SUBMIT_TASK = 'SUBMIT_TASK'

// Announments
export const GET_USER_ANNOUNCEMENTS = 'GET_USER_ANNOUNCEMENTS'
export const UPDATE_USER_ANNOUNCEMENT = 'UPDATE_USER_ANNOUNCEMENT'


// Clear Data 
export const CLEAR_ALL_DATA = 'CLEAR_ALL_DATA'
